### ISSUE TITLE
Display Port usage? external display methods?

### ISSUE THREAD

**Issue by k4kanwar** [muhrizki1996/Hackintosh-Lenovo-ThinkPad-X230#1]
Can we get a confirmation on DP port usage? does it allow it?

**Comment by muhrizki1996** [comment]
> Can we get a confirmation on DP port usage? does it allow it?

Yesterday, my miniDP to HDMI was Arrived.. and when i'm tested, nothing display on the TV but the TV was detected on Display Preferences and Mirroring on Menu Bar.. still wanna to figure out what's the problem

**Comment by muhrizki1996** [comment]
> Can we get a confirmation on DP port usage? does it allow it?

i purchase new miniDP to HDMI from my local store.. and it works..
![IMG_0908](https://user-images.githubusercontent.com/46028018/146898464-1906bf00-3a41-40cc-a0bc-3f8e225eb24c.JPG)
also tested on latest macOS Monterey 12.1 (21C52) works really well..
